# Global properties go here
spring:
   profiles:
      active: test
   main:
      allow-bean-definition-overriding: true
   datasource:
      # this maps to an in-memory database that lives within a single VM.
      # in case you want to use H2 with a file persistence or as a service
      # reference http://www.h2database.com/html/cheatSheet.html and
      # http://www.h2database.com/html/tutorial.html#using_server
      url: jdbc:h2:mem:testtest
      driver-class-name: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect

mvc:
   iex:
      getAllSymbolsPath: /iex/symbols
      getLastTradedPricePath: /iex/lastTradedPrice
   av:
      getDailyTimeSeries: /prices
   max-size-trace-payload: 50000
jms:
   listener-concurrency: 1-5
   agreement-queue-json: sandbox.agreement
   agreement-queue-proto: sandbox.agreement.proto

# Set debug level logging for the IEX Client so that Feign requests and responses are logged out
log.level.org.galatea.starter.service.IEXClient: DEBUG
# Set info level logging for the autoconfigure package so that it doesn't print out the entire
# CONDITIONS EVALUATION REPORT on startup
logging.level.org.springframework.boot.autoconfigure: INFO

---
# Test properties go here
spring:
   profiles: test
   datasource:
      username: sa
      password:
   api:
      config:
         avApiKey: REALLYCOOLKEYHERE
   rest:
      # this points at the local WireMock server in the test environment.
      avBasePath: http://localhost:${wiremock.server.port}/

---
# Dev properties go here

spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://localhost:3306/galatea_starter
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: sa
      password: Am!8_jag#_!cn^rK$OC1&(i3$mK7XX#p6KLhG2(kU3xfBffz41O2*ERU74kO1itj
   api:
      config:
         avApiKey: RE1VLFFM7J2OSXLK
   rest:
      avBasePath: https://www.alphavantage.co
      avRequestDaily: query?function=TIME_SERIES_DAILY
jpa:
   hibernate.ddl-auto: update
   generate-ddl: false
   show-sql: false
   properties:
      hibernate:
         dialect: org.hibernate.dialect.H2Dialect
# set debug to get spring to log the classpath (and other things) on startup
debug: true

---
# UAT properties go here
spring:
   profiles: uat
   datasource:
      username: sa
      password:

---
# Mappings for Rest Controllers
webservice:
